version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=simple_password
      - DB_NAME=launchpad_db
      - GIN_MODE=release
    networks:
      - launchpad-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=simple_password
      - MYSQL_DATABASE=launchpad_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - launchpad-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  launchpad-network:
    driver: bridge 