version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=launchpad_user
      - DB_PASSWORD=launchpad_password
      - DB_NAME=launchpad_db
    networks:
      - launchpad-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=launchpad_db
      - MYSQL_USER=launchpad_user
      - MYSQL_PASSWORD=launchpad_password
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - launchpad-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  launchpad-network:
    driver: bridge
