version: "3.8"

services:
  app:
    image: ghcr.io/amiklosi/lm-backend-go:latest
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=launchpad_user
      - DB_PASSWORD=${DB_PASSWORD:-launchpad_password}
      - DB_NAME=launchpad_db
      - GIN_MODE=release
    networks:
      - launchpad-network
      - traefik_default
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launchpad.rule=Host(`lmgo.launchpadmanager.com`)"
      - "traefik.http.routers.launchpad.entrypoints=web-secure"
      - "traefik.http.routers.launchpad.tls.certresolver=certificato"
      - "traefik.http.services.launchpad.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_default"

  db:
    image: ghcr.io/amiklosi/lm-backend-go-mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=launchpad_db
      - MYSQL_USER=launchpad_user
      - MYSQL_PASSWORD=${DB_PASSWORD:-launchpad_password}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - launchpad-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root_password}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:

networks:
  launchpad-network:
    driver: bridge
  traefik_default:
    external: true
