version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=launchpad_user
      - DB_PASSWORD=launchpad_password
      - DB_NAME=launchpad_db
      - GIN_MODE=release
    networks:
      - launchpad-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launchpad.rule=Host(`lmgo.launchpadmanager.com`)"
      - "traefik.http.routers.launchpad.entrypoints=websecure"
      - "traefik.http.routers.launchpad.tls.certresolver=certificato"
      - "traefik.http.services.launchpad.loadbalancer.server.port=8080"

  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=launchpad_db
      - MYSQL_USER=launchpad_user
      - MYSQL_PASSWORD=launchpad_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - launchpad-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  launchpad-network:
    driver: bridge
