version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=test_db
    command: --authentication-policy=caching_sha2_password
    volumes:
      - test_mysql_data:/var/lib/mysql
    networks:
      - test-network
    restart: unless-stopped

  test:
    image: mysql:8.0
    depends_on:
      - db
    command: >
      sh -c "
        echo 'Waiting for MySQL...' &&
        sleep 30 &&
        echo 'Testing root connection...' &&
        mysql -h db -u root -ptest123 -e 'SELECT 1 as test;' &&
        echo 'Root connection successful!' &&
        echo 'Testing user creation...' &&
        mysql -h db -u root -ptest123 -e 'CREATE USER IF NOT EXISTS \"testuser\"@\"%\" IDENTIFIED WITH caching_sha2_password BY \"testpass\";' &&
        echo 'User created successfully!' &&
        echo 'Testing user connection...' &&
        mysql -h db -u testuser -ptestpass -e 'SELECT 1 as test;' &&
        echo 'User connection successful!'
      "
    networks:
      - test-network

volumes:
  test_mysql_data:

networks:
  test-network:
    driver: bridge
